In [2]:
#importing the libraries needed 
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
from time import sleep
from random import randint

#Declaring the headers 
headers = {"Accept-Language": "en-US,en;q=0.5"}

#declaring the list of empty variables, So that we can append the data overall
#creating an array of values and passing it in the url for dynamic webpages


#the whole core of the script
#creating an array of values and passing it in the url for dynamic webpages


metascore =[]
gross = []
#the whole core of the script

page = requests.get("https://www.imdb.com/search/title/?genres=action&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=f11158cc-b50b-4c4d-b0a2-40b32863395b&pf_rd_r=XZ8X52H1R40B7KG5SNZ9&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_1")
soup = BeautifulSoup(page.text, 'html.parser')
movie_data = soup.findAll('div', attrs = {'class': 'lister-item mode-advanced'})

for store in movie_data:
    meta = store.find('span', class_ = "metascore").text if store.find('span', class_ = "metascore") else "NA"
    metascore.append(meta)


    value = store.find_all('span', attrs = {'name': "nv"})


    grosses = value[1].text if len(value)>1 else 'NA'
    gross.append(grosses)

len(metascore)

50

In [3]:
import selenium
import warnings
import pandas as pd
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

s=Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=s)
driver.maximize_window()

#linking Site

driver.get("https://www.imdb.com/search/title/?genres=action&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=f11158cc-b50b-4c4d-b0a2-40b32863395b&pf_rd_r=XZ8X52H1R40B7KG5SNZ9&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_1")

time.sleep(5)

Name=[]
Years=[]
Ratings=[]
Votes=[]
Genre1=[]
Genre2=[]
Genre3=[]
Runtime=[]
Metascore=[]
Director=[]
Certificate=[]
Gross=[]
Stars=[]

try:
    name=driver.find_elements(By.XPATH,"//*[@id='main']/div/div[3]/div/div/div[3]/h3/a")

    for i in name:
        Name.append(i.text)     #Scraping name list

except NoSuchElementException:
    Name.append("-")

try:
    span=driver.find_elements(By.XPATH,'//*[@id="main"]/div/div[3]/div/div/div[3]/h3/span[2]')

    for i in span:
        Years.append(i.text)          #Scraping Year span

except NoSuchElementException:
    Years.append("-")

try:
    genre=driver.find_elements(By.XPATH,'//span[@class="genre"]')

    for i in genre:
        x=i.text.split(",")
        if(len(x)==1):
            Genre1.append(x[0])
            Genre2.append("-")
            Genre3.append("-")
        elif(len(x)==2):
            Genre1.append(x[0])
            Genre2.append(x[1])
            Genre3.append("-")
        else:
            Genre1.append(x[0])
            Genre2.append(x[1])
            Genre3.append(x[2])

except NoSuchElementException:
    Genre.append("-")
try:
    runtime=driver.find_elements(By.XPATH,'//span[@class="runtime"]')
    for i in runtime:
        Runtime.append(i.text.strip("min"))      #Scraping Runtime

except NoSuchElementException:
    Runtime.append("-")
    
    
try:
    rating=driver.find_elements(By.XPATH,'//div[@class="inline-block ratings-imdb-rating"]')
    for i in rating:
        Ratings.append(i.text)            #Scraping Rating

except NoSuchElementException:
    Ratings.append("-")
    
try:
    vote=driver.find_elements(By.XPATH,'//*[@id="main"]/div/div[3]/div/div/div[3]/p[4]/span[2]')
    for i in vote:
        Votes.append(i.text)            #Scraping votes

except NoSuchElementException:
    Votes.append("-")
    


    

    
try:
    certt=driver.find_elements(By.XPATH,'//*[@id="main"]/div/div[3]/div/div/div[3]/p[1]/span[1]')
    
    for i in certt:
        Certificate.append(i.text)            #Scraping Certificate

except NoSuchElementException:
    Certificate.append("-")
    


Cast=[]
Dir1=[]
Dir2=[]
Dir3=[]
Actor1=[]
Actor2=[]
Actor3=[]
Actor4=[]
Cast1=[]
Cast2=[]

try:
    actor=driver.find_elements(By.XPATH,'//*[@id="main"]/div/div[3]/div/div/div[3]/p[3]')
    
    for i in actor:
        y=i.text.split("|")
        Cast1.append(y[0])
        Cast2.append(y[1])
        
        
                                       #Scraping Stars

except NoSuchElementException:
    Cast.append("-")
    
n=len(Cast1)
for i in range(0,n):
    str1=Cast1[i]
    x=str1.split(",")
    if(len(x)==1):
        temp=x[0]
        y=temp.split(":")
        Dir1.append(y[1])
        Dir2.append("-")
        Dir3.append("-")
    elif(len(x)==2):
        temp=x[0]
        y=temp.split(":")
        Dir1.append(y[1])
        Dir2.append(x[1])
        Dir3.append("-")
    else:
        temp=x[0]
        y=temp.split(":")
        Dir1.append(y[1])
        Dir2.append(x[1])
        Dir3.append(x[2])

k=len(Cast2)
for i in range(0,k):
    str1=Cast2[i]
    x=str1.split(",")
    if(len(x)==1):
        temp=x[0]
        y=temp.split(":")
        Actor1.append(y[1])
        Actor2.append("-")
        Actor3.append("-")
        Actor4.append("-")
    elif(len(x)==2):
        temp=x[0]
        y=temp.split(":")
        Actor1.append(y[1])
        Actor2.append(x[1])
        Actor3.append("-")
        Actor4.append("-") 
    elif(len(x)==3):
        temp=x[0]
        y=temp.split(":")
        Actor1.append(y[1])
        Actor2.append(x[1])
        Actor3.append(x[2])
        Actor4.append("-")
    else:
        temp=x[0]
        y=temp.split(":")
        Actor1.append(y[1])
        Actor2.append(x[1])
        Actor3.append(x[2])
        Actor4.append(x[3])
    
df1=pd.DataFrame({"Name":Name,"Dir1":Dir1,"Dir2":Dir2,
                  "Dir3":Dir3,"Years":Years,
                 "Runtime":Runtime,"Ratings":Ratings,"metascore":metascore})
                  
df2=pd.DataFrame({"Name":Name,"Actor1":Actor1,"Actor2":Actor2,"Actor3":Actor3,
                  "Actor4":Actor4,"Genre1":Genre1,"Genre2":Genre2,
                  "Genre3":Genre3,"Votes":Votes,
                 "Certificate" : Certificate,"gross":gross})




#Movie Name, Director Name, Duration, year, ratings, Metascore

#Movie Name, stars, votes, Genre, Gross collection, popularity, Certification

In [4]:
df1

,Name,Dir1,Dir2,Dir3,Years,Runtime,Ratings,metascore
0,Spider-Man: Across the Spider-Verse,Joaquim Dos Santos,Kemp Powers,Justin K. Thompson,(2023),140,9.1,87
1,The Dark Knight,Christopher Nolan,-,-,(2008),152,9.0,84
2,The Lord of the Rings: The Return of the King,Peter Jackson,-,-,(2003),201,9.0,94
3,Inception,Christopher Nolan,-,-,(2010),148,8.8,74
4,The Lord of the Rings: The Fellowship of the Ring,Peter Jackson,-,-,(2001),178,8.8,92
5,The Lord of the Rings: The Two Towers,Peter Jackson,-,-,(2002),179,8.8,87
6,The Matrix,Lana Wachowski,Lilly Wachowski,-,(1999),136,8.7,73
7,Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,-,-,(1980),124,8.7,82
8,Soorarai Pottru,Sudha Kongara,-,-,(2020),153,8.7,NA
9,Star Wars: Episode IV - A New Hope,George Lucas,-,-,(1977),121,8.6,90
10,Terminator 2: Judgment Day,James Cameron,-,-,(1991),137,8.6,75
11,Seven Samurai,Akira Kurosawa,-,-,(1954),207,8.6,98
12,Harakiri,Masaki Kobayashi,-,-,(1962),133,8.6,85
13,Sita Ramam,Hanu Raghavapudi,-,-,(2022),163,8.6,NA
14,Léon: The Professional,Luc Besson,-,-,(1994),110,8.5,64
15,Gladiator,Ridley Scott,-,-,(2000),155,8.5,67
16,Spider-Man: Into the Spider-Verse,Bob Persichetti,Peter Ramsey,Rodney Rothman,(2018),117,8.4,87
17,Indiana Jones and the Raiders of the Lost Ark,Steven Spielberg,-,-,(1981),115,8.4,85
18,Avengers: Endgame,Anthony Russo,Joe Russo,-,(2019),181,8.4,78
19,Avengers: Infinity War,Anthony Russo,Joe Russo,-,(2018),149,8.4,68
20,Oldboy,Park Chan-wook,-,-,(2003),101,8.4,77
21,The Dark Knight Rises,Christopher Nolan,-,-,(2012),164,8.4,78
22,Aliens,James Cameron,-,-,(1986),137,8.4,84
23,Kaithi,Lokesh Kanagaraj,-,-,(2019),145,8.4,NA
24,Asuran,Vetrimaaran,-,-,(2019),141,8.4,NA
25,Top Gun: Maverick,Joseph Kosinski,-,-,(2022),130,8.3,78
26,Heat,Michael Mann,-,-,(1995),170,8.3,76
27,North by Northwest,Alfred Hitchcock,-,-,(1959),136,8.3,98
28,Star Wars: Episode VI - Return of the Jedi,Richard Marquand,-,-,(1983),131,8.3,58
29,Princess Mononoke,Hayao Miyazaki,-,-,(1997),134,8.3,76
30,Kantara,Rishab Shetty,-,-,(2022),148,8.3,NA
31,Dangal,Nitesh Tiwari,-,-,(2016),161,8.3,NA
32,Raatchasan,Ram Kumar,-,-,(2018),170,8.3,NA
33,K.G.F: Chapter 2,Prashanth Neel,-,-,(2022),168,8.3,NA
34,Vikram,Lokesh Kanagaraj,-,-,(2022),175,8.3,NA
35,Shershaah,Vishnuvardhan,-,-,(2021),135,8.3,NA
36,Guardians of the Galaxy Vol. 3,James Gunn,-,-,(2023),150,8.2,64
37,Spider-Man: No Way Home,Jon Watts,-,-,(2021),148,8.2,71
38,Jurassic Park,Steven Spielberg,-,-,(1993),127,8.2,68
39,Indiana Jones and the Last Crusade,Steven Spielberg,-,-,(1989),127,8.2,65
40,1917,Sam Mendes,-,-,(2019),119,8.2,78
41,Batman Begins,Christopher Nolan,-,-,(2005),140,8.2,70
42,Kill Bill: Vol. 1,Quentin Tarantino,-,-,(2003),111,8.2,69
43,Die Hard,John McTiernan,-,-,(1988),132,8.2,72
44,V for Vendetta,James McTeigue,-,-,(2005),132,8.2,62
45,Warrior,Gavin O'Connor,-,-,(2011),140,8.2,71
46,Demon Slayer the Movie: Mugen Train,Haruo Sotozaki,-,-,(2020),117,8.2,72
47,Ran,Akira Kurosawa,-,-,(1985),162,8.2,97
48,Gangs of Wasseypur,Anurag Kashyap,-,-,(2012),321,8.2,89
49,Vikram Vedha,Gayatri,Pushkar,Gowtham Selvaraj,(2017),147,8.2,NA

In [5]:
df2

,Name,Actor1,Actor2,Actor3,Actor4,Genre1,Genre2,Genre3,Votes,Certificate,gross
0,Spider-Man: Across the Spider-Verse,Shameik Moore,Hailee Steinfeld,Brian Tyree Henry,Luna Lauren Velez,Animation,Action,Adventure,"62,493",PG,NA
1,The Dark Knight,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,Action,Crime,Drama,"2,720,714",PG-13,$534.86M
2,The Lord of the Rings: The Return of the King,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,Action,Adventure,Drama,"1,888,488",PG-13,$377.85M
3,Inception,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,Action,Adventure,Sci-Fi,"2,415,029",PG-13,$292.58M
4,The Lord of the Rings: The Fellowship of the Ring,Elijah Wood,Ian McKellen,Orlando Bloom,Sean Bean,Action,Adventure,Drama,"1,917,095",PG-13,$315.54M
5,The Lord of the Rings: The Two Towers,Elijah Wood,Ian McKellen,Viggo Mortensen,Orlando Bloom,Action,Adventure,Drama,"1,704,482",PG-13,$342.55M
6,The Matrix,Keanu Reeves,Laurence Fishburne,Carrie-Anne Moss,Hugo Weaving,Action,Sci-Fi,-,"1,959,384",R,$171.48M
7,Star Wars: Episode V - The Empire Strikes Back,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,Action,Adventure,Fantasy,"1,322,132",PG,$290.48M
8,Soorarai Pottru,Suriya,Paresh Rawal,Urvashi,Aparna Balamurali,Action,Drama,-,"119,546",TV-MA,NA
9,Star Wars: Episode IV - A New Hope,Mark Hamill,Harrison Ford,Carrie Fisher,Alec Guinness,Action,Adventure,Fantasy,"1,394,569",PG,$322.74M
10,Terminator 2: Judgment Day,Arnold Schwarzenegger,Linda Hamilton,Edward Furlong,Robert Patrick,Action,Sci-Fi,-,"1,123,864",R,$204.84M
11,Seven Samurai,Toshirô Mifune,Takashi Shimura,Keiko Tsushima,Yukiko Shimazaki,Action,Drama,-,"353,024",Not Rated,$0.27M
12,Harakiri,Tatsuya Nakadai,Akira Ishihama,Shima Iwashita,Tetsurô Tanba,Action,Drama,Mystery,"61,080",Not Rated,NA
13,Sita Ramam,Dulquer Salmaan,Mrunal Thakur,Rashmika Mandanna,Sumanth,Action,Drama,Mystery,"60,080",U,NA
14,Léon: The Professional,Jean Reno,Gary Oldman,Natalie Portman,Danny Aiello,Action,Crime,Drama,"1,190,290",R,$19.50M
15,Gladiator,Russell Crowe,Joaquin Phoenix,Connie Nielsen,Oliver Reed,Action,Adventure,Drama,"1,537,247",R,$187.71M
16,Spider-Man: Into the Spider-Verse,Shameik Moore,Jake Johnson,Hailee Steinfeld,Mahershala Ali,Animation,Action,Adventure,"573,622",PG,$190.24M
17,Indiana Jones and the Raiders of the Lost Ark,Harrison Ford,Karen Allen,Paul Freeman,John Rhys-Davies,Action,Adventure,-,"987,533",PG,$248.16M
18,Avengers: Endgame,Robert Downey Jr.,Chris Evans,Mark Ruffalo,Chris Hemsworth,Action,Adventure,Drama,"1,181,738",PG-13,$858.37M
19,Avengers: Infinity War,Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo,Chris Evans,Action,Adventure,Sci-Fi,"1,125,020",PG-13,$678.82M
20,Oldboy,Choi Min-sik,Yoo Ji-tae,Kang Hye-jeong,Kim Byeong-Ok,Action,Drama,Mystery,"596,893",R,$0.71M
21,The Dark Knight Rises,Christian Bale,Tom Hardy,Anne Hathaway,Gary Oldman,Action,Drama,Thriller,"1,742,890",PG-13,$448.14M
22,Aliens,Sigourney Weaver,Michael Biehn,Carrie Henn,Paul Reiser,Action,Adventure,Sci-Fi,"732,966",R,$85.16M
23,Kaithi,Karthi,Narain,Arjun Das,George Maryan,Action,Adventure,Crime,"36,165",Not Rated,NA
24,Asuran,Dhanush,Manju Warrier,Prakash Raj,Pasupathy,Action,Drama,-,"31,220",Not Rated,NA
25,Top Gun: Maverick,Tom Cruise,Jennifer Connelly,Miles Teller,Val Kilmer,Action,Drama,-,"591,986",PG-13,$718.73M
26,Heat,Al Pacino,Robert De Niro,Val Kilmer,Jon Voight,Action,Crime,Drama,"677,168",R,$67.44M
27,North by Northwest,Cary Grant,Eva Marie Saint,James Mason,Jessie Royce Landis,Action,Adventure,Mystery,"334,789",Approved,$13.28M
28,Star Wars: Episode VI - Return of the Jedi,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,Action,Adventure,Fantasy,"1,078,394",PG,$309.13M
29,Princess Mononoke,Yôji Matsuda,Yuriko Ishida,Yûko Tanaka,Billy Crudup,Animation,Action,Adventure,"407,126",PG-13,$2.38M
30,Kantara,Rishab Shetty,Kishore Kumar G.,Achyuth Kumar,Sapthami Gowda,Action,Adventure,Drama,"95,587",Not Rated,NA
31,Dangal,Aamir Khan,Sakshi Tanwar,Fatima Sana Shaikh,Sanya Malhotra,Action,Biography,Drama,"197,494",Not Rated,$12.39M
32,Raatchasan,Vishnu Vishal,Amala Paul,Radha Ravi,Sangili Murugan,Action,Crime,Drama,"46,986",Not Rated,NA
33,K.G.F: Chapter 2,Yash,Sanjay Dutt,Raveena Tandon,Srinidhi Shetty,Action,Crime,Drama,"139,725",Not Rated,$6.60M
34,Vikram,Kamal Haasan,Vijay Sethupathi,Fahadh Faasil,Narain,Action,Crime,Thriller,"63,915",UA,NA
35,Shershaah,Sidharth Malhotra,Kiara Advani,Shiv Panditt,Pranay Pachauri,Action,Biography,Drama,"124,855",TV-14,NA
36,Guardians of the Galaxy Vol. 3,Chris Pratt,Chukwudi Iwuji,Bradley Cooper,Pom Klementieff,Action,Adventure,Comedy,"158,924",PG-13,NA
37,Spider-Man: No Way Home,Tom Holland,Zendaya,Benedict Cumberbatch,Jacob Batalon,Action,Adventure,Fantasy,"798,894",PG-13,$804.75M
38,Jurassic Park,Sam Neill,Laura Dern,Jeff Goldblum,Richard Attenborough,Action,Adventure,Sci-Fi,"1,014,680",PG-13,$402.45M
39,Indiana Jones and the Last Crusade,Harrison Ford,Sean Connery,Alison Doody,Denholm Elliott,Action,Adventure,-,"771,853",PG-13,$197.17M
40,1917,Dean-Charles Chapman,George MacKay,Daniel Mays,Colin Firth,Action,Drama,War,"621,858",R,$159.23M
41,Batman Begins,Christian Bale,Michael Caine,Ken Watanabe,Liam Neeson,Action,Crime,Drama,"1,504,287",PG-13,$206.85M
42,Kill Bill: Vol. 1,Uma Thurman,David Carradine,Daryl Hannah,Michael Madsen,Action,Crime,Drama,"1,141,500",R,$70.10M
43,Die Hard,Bruce Willis,Alan Rickman,Bonnie Bedelia,Reginald VelJohnson,Action,Thriller,-,"901,796",R,$83.01M
44,V for Vendetta,Hugo Weaving,Natalie Portman,Rupert Graves,Stephen Rea,Action,Drama,Sci-Fi,"1,141,357",R,$70.51M
45,Warrior,Tom Hardy,Nick Nolte,Joel Edgerton,Jennifer Morrison,Action,Drama,Sport,"482,049",PG-13,$13.66M
46,Demon Slayer the Movie: Mugen Train,Natsuki Hanae,Akari Kitô,Yoshitsugu Matsuoka,Hiro Shimono,Animation,Action,Adventure,"64,529",R,$47.70M
47,Ran,Tatsuya Nakadai,Akira Terao,Jinpachi Nezu,Daisuke Ryû,Action,Drama,War,"129,266",R,$4.14M
48,Gangs of Wasseypur,Manoj Bajpayee,Nawazuddin Siddiqui,Tigmanshu Dhulia,Richa Chadha,Action,Comedy,Crime,"99,407",Not Rated,NA
49,Vikram Vedha,Madhavan,Vijay Sethupathi,Shraddha Srinath,Kathir,Action,Crime,Drama,"47,722",Not Rated,NA

In [6]:
df1.to_csv("C:/Users/Pooja/Downloads/Data/File1.csv")
df2.to_csv("C:/Users/Pooja/Downloads/Data/File2.csv")

In [7]:
import sqlite3

sqliteConnection = sqlite3.connect('data.db')
cursor = sqliteConnection.cursor()
print("Connected to the database")

Connected to the database

In [8]:
# execute the statement
cursor.execute("""CREATE TABLE Imdb100 (Name TEXT,Dir1 TEXT,Dir2 TEXT,Dir3 TEXT,Years TEXT,
                 Runtime REAL ,Ratings INTEGER,metascore REAL)""")

In [19]:
with open('C:/Users/Pooja/Downloads/Data/File1.csv','r') as file:
    total=0
    for row in file :
        cursor.execute("insert into Imdb100 values(?,?,?,?,?,?,?,?)",row.split(","))
        sqliteConnection.commit()
        total+=1
print(total,'Records Inserted')

51 Records Inserted

In [20]:
result=cursor.execute("SELECT * FROM Imdb100")
for row in result:
    print(row)

('Name', 'Dir1', 'Dir2', 'Dir3', 'Years', 'Runtime', 'Ratings', 'metascore\n')
('Spider-Man: Across the Spider-Verse', ' Joaquim Dos Santos', ' Kemp Powers', ' Justin K. Thompson ', '-2023', 140.0, 9.1, 87.0)
('The Dark Knight', ' Christopher Nolan ', '-', '-', '-2008', 152.0, 9, 84.0)
('The Lord of the Rings: The Return of the King', ' Peter Jackson ', '-', '-', '-2003', 201.0, 9, 94.0)
('Inception', ' Christopher Nolan ', '-', '-', '-2010', 148.0, 8.8, 74.0)
('The Lord of the Rings: The Fellowship of the Ring', ' Peter Jackson ', '-', '-', '-2001', 178.0, 8.8, 92.0)
('The Lord of the Rings: The Two Towers', ' Peter Jackson ', '-', '-', '-2002', 179.0, 8.8, 87.0)
('The Matrix', ' Lana Wachowski', ' Lilly Wachowski ', '-', '-1999', 136.0, 8.7, 73.0)
('Star Wars: Episode V - The Empire Strikes Back', ' Irvin Kershner ', '-', '-', '-1980', 124.0, 8.7, 82.0)
('Soorarai Pottru', ' Sudha Kongara ', '-', '-', '-2020', 153.0, 8.7, 'NA\n')
('Star Wars: Episode IV - A New Hope', ' George Lucas ', '-', '-', '-1977', 121.0, 8.6, 90.0)
('Terminator 2: Judgment Day', ' James Cameron ', '-', '-', '-1991', 137.0, 8.6, 75.0)
('Seven Samurai', ' Akira Kurosawa ', '-', '-', '-1954', 207.0, 8.6, 98.0)
('Harakiri', ' Masaki Kobayashi ', '-', '-', '-1962', 133.0, 8.6, 85.0)
('Sita Ramam', ' Hanu Raghavapudi ', '-', '-', '-2022', 163.0, 8.6, 'NA\n')
('LÃ©on: The Professional', ' Luc Besson ', '-', '-', '-1994', 110.0, 8.5, 64.0)
('Gladiator', ' Ridley Scott ', '-', '-', '-2000', 155.0, 8.5, 67.0)
('Spider-Man: Into the Spider-Verse', ' Bob Persichetti', ' Peter Ramsey', ' Rodney Rothman ', '-2018', 117.0, 8.4, 87.0)
('Indiana Jones and the Raiders of the Lost Ark', ' Steven Spielberg ', '-', '-', '-1981', 115.0, 8.4, 85.0)
('Avengers: Endgame', ' Anthony Russo', ' Joe Russo ', '-', '-2019', 181.0, 8.4, 78.0)
('Avengers: Infinity War', ' Anthony Russo', ' Joe Russo ', '-', '-2018', 149.0, 8.4, 68.0)
('Oldboy', ' Park Chan-wook ', '-', '-', '-2003', 101.0, 8.4, 77.0)
('The Dark Knight Rises', ' Christopher Nolan ', '-', '-', '-2012', 164.0, 8.4, 78.0)
('Aliens', ' James Cameron ', '-', '-', '-1986', 137.0, 8.4, 84.0)
('Kaithi', ' Lokesh Kanagaraj ', '-', '-', '-2019', 145.0, 8.4, 'NA\n')
('Asuran', ' Vetrimaaran ', '-', '-', '-2019', 141.0, 8.4, 'NA\n')
('Top Gun: Maverick', ' Joseph Kosinski ', '-', '-', '-2022', 130.0, 8.3, 78.0)
('Heat', ' Michael Mann ', '-', '-', '-1995', 170.0, 8.3, 76.0)
('North by Northwest', ' Alfred Hitchcock ', '-', '-', '-1959', 136.0, 8.3, 98.0)
('Star Wars: Episode VI - Return of the Jedi', ' Richard Marquand ', '-', '-', '-1983', 131.0, 8.3, 58.0)
('Princess Mononoke', ' Hayao Miyazaki ', '-', '-', '-1997', 134.0, 8.3, 76.0)
('Kantara', ' Rishab Shetty ', '-', '-', '-2022', 148.0, 8.3, 'NA\n')
('Dangal', ' Nitesh Tiwari ', '-', '-', '-2016', 161.0, 8.3, 'NA\n')
('Raatchasan', ' Ram Kumar ', '-', '-', '-2018', 170.0, 8.3, 'NA\n')
('K.G.F: Chapter 2', ' Prashanth Neel ', '-', '-', '-2022', 168.0, 8.3, 'NA\n')
('Vikram', ' Lokesh Kanagaraj ', '-', '-', '-2022', 175.0, 8.3, 'NA\n')
('Shershaah', ' Vishnuvardhan ', '-', '-', '-2021', 135.0, 8.3, 'NA\n')
('Guardians of the Galaxy Vol. 3', ' James Gunn ', '-', '-', '-2023', 150.0, 8.2, 64.0)
('Spider-Man: No Way Home', ' Jon Watts ', '-', '-', '-2021', 148.0, 8.2, 71.0)
('Jurassic Park', ' Steven Spielberg ', '-', '-', '-1993', 127.0, 8.2, 68.0)
('Indiana Jones and the Last Crusade', ' Steven Spielberg ', '-', '-', '-1989', 127.0, 8.2, 65.0)
('1917', ' Sam Mendes ', '-', '-', '-2019', 119.0, 8.2, 78.0)
('Batman Begins', ' Christopher Nolan ', '-', '-', '-2005', 140.0, 8.2, 70.0)
('Kill Bill: Vol. 1', ' Quentin Tarantino ', '-', '-', '-2003', 111.0, 8.2, 69.0)
('Die Hard', ' John McTiernan ', '-', '-', '-1988', 132.0, 8.2, 72.0)
('V for Vendetta', ' James McTeigue ', '-', '-', '-2005', 132.0, 8.2, 62.0)
('Warrior', " Gavin O'Connor ", '-', '-', '-2011', 140.0, 8.2, 71.0)
('Demon Slayer the Movie: Mugen Train', ' Haruo Sotozaki ', '-', '-', '-2020', 117.0, 8.2, 72.0)
('Ran', ' Akira Kurosawa ', '-', '-', '-1985', 162.0, 8.2, 97.0)
('Gangs of Wasseypur', ' Anurag Kashyap ', '-', '-', '-2012', 321.0, 8.2, 89.0)
('Vikram Vedha', ' Gayatri', ' Pushkar', ' Gowtham Selvaraj ', '-2017', 147.0, 8.2, 'NA\n')

1)  Display all the details of movies created by directors Christopher and Matt Reeves.

In [25]:
sql="SELECT * FROM Imdb100 WHERE Dir1 LIKE '%Matt%' "
result=cursor.execute(sql) 


for i in result:
    print(i)

In [24]:
sql="SELECT * FROM Imdb100 WHERE Dir1 LIKE '%Christopher%' "
result=cursor.execute(sql) 


for i in result:
    print(i)

('The Dark Knight', ' Christopher Nolan ', '-', '-', '-2008', 152.0, 9, 84.0)
('Inception', ' Christopher Nolan ', '-', '-', '-2010', 148.0, 8.8, 74.0)
('The Dark Knight Rises', ' Christopher Nolan ', '-', '-', '-2012', 164.0, 8.4, 78.0)
('Batman Begins', ' Christopher Nolan ', '-', '-', '-2005', 140.0, 8.2, 70.0)

2) Display all the details of movies with a duration of 140 minutes to 190 minutes.

In [28]:
sql="SELECT * FROM Imdb100 WHERE Runtime >=140 AND Runtime<=190"
result=cursor.execute(sql)

for i in result:
    print(i)

('Spider-Man: Across the Spider-Verse', ' Joaquim Dos Santos', ' Kemp Powers', ' Justin K. Thompson ', '-2023', 140.0, 9.1, 87.0)
('The Dark Knight', ' Christopher Nolan ', '-', '-', '-2008', 152.0, 9, 84.0)
('Inception', ' Christopher Nolan ', '-', '-', '-2010', 148.0, 8.8, 74.0)
('The Lord of the Rings: The Fellowship of the Ring', ' Peter Jackson ', '-', '-', '-2001', 178.0, 8.8, 92.0)
('The Lord of the Rings: The Two Towers', ' Peter Jackson ', '-', '-', '-2002', 179.0, 8.8, 87.0)
('Soorarai Pottru', ' Sudha Kongara ', '-', '-', '-2020', 153.0, 8.7, 'NA\n')
('Sita Ramam', ' Hanu Raghavapudi ', '-', '-', '-2022', 163.0, 8.6, 'NA\n')
('Gladiator', ' Ridley Scott ', '-', '-', '-2000', 155.0, 8.5, 67.0)
('Avengers: Endgame', ' Anthony Russo', ' Joe Russo ', '-', '-2019', 181.0, 8.4, 78.0)
('Avengers: Infinity War', ' Anthony Russo', ' Joe Russo ', '-', '-2018', 149.0, 8.4, 68.0)
('The Dark Knight Rises', ' Christopher Nolan ', '-', '-', '-2012', 164.0, 8.4, 78.0)
('Kaithi', ' Lokesh Kanagaraj ', '-', '-', '-2019', 145.0, 8.4, 'NA\n')
('Asuran', ' Vetrimaaran ', '-', '-', '-2019', 141.0, 8.4, 'NA\n')
('Heat', ' Michael Mann ', '-', '-', '-1995', 170.0, 8.3, 76.0)
('Kantara', ' Rishab Shetty ', '-', '-', '-2022', 148.0, 8.3, 'NA\n')
('Dangal', ' Nitesh Tiwari ', '-', '-', '-2016', 161.0, 8.3, 'NA\n')
('Raatchasan', ' Ram Kumar ', '-', '-', '-2018', 170.0, 8.3, 'NA\n')
('K.G.F: Chapter 2', ' Prashanth Neel ', '-', '-', '-2022', 168.0, 8.3, 'NA\n')
('Vikram', ' Lokesh Kanagaraj ', '-', '-', '-2022', 175.0, 8.3, 'NA\n')
('Guardians of the Galaxy Vol. 3', ' James Gunn ', '-', '-', '-2023', 150.0, 8.2, 64.0)
('Spider-Man: No Way Home', ' Jon Watts ', '-', '-', '-2021', 148.0, 8.2, 71.0)
('Batman Begins', ' Christopher Nolan ', '-', '-', '-2005', 140.0, 8.2, 70.0)
('Warrior', " Gavin O'Connor ", '-', '-', '-2011', 140.0, 8.2, 71.0)
('Ran', ' Akira Kurosawa ', '-', '-', '-1985', 162.0, 8.2, 97.0)
('Vikram Vedha', ' Gayatri', ' Pushkar', ' Gowtham Selvaraj ', '-2017', 147.0, 8.2, 'NA\n')

3) Display all details of movies with ratings above 7 in ascending order.

In [29]:
sql1="SELECT * FROM Imdb100 WHERE Ratings>7 ORDER BY Ratings ASC"
result=cursor.execute(sql1)


for i in result:
    print(i)

('Guardians of the Galaxy Vol. 3', ' James Gunn ', '-', '-', '-2023', 150.0, 8.2, 64.0)
('Spider-Man: No Way Home', ' Jon Watts ', '-', '-', '-2021', 148.0, 8.2, 71.0)
('Jurassic Park', ' Steven Spielberg ', '-', '-', '-1993', 127.0, 8.2, 68.0)
('Indiana Jones and the Last Crusade', ' Steven Spielberg ', '-', '-', '-1989', 127.0, 8.2, 65.0)
('1917', ' Sam Mendes ', '-', '-', '-2019', 119.0, 8.2, 78.0)
('Batman Begins', ' Christopher Nolan ', '-', '-', '-2005', 140.0, 8.2, 70.0)
('Kill Bill: Vol. 1', ' Quentin Tarantino ', '-', '-', '-2003', 111.0, 8.2, 69.0)
('Die Hard', ' John McTiernan ', '-', '-', '-1988', 132.0, 8.2, 72.0)
('V for Vendetta', ' James McTeigue ', '-', '-', '-2005', 132.0, 8.2, 62.0)
('Warrior', " Gavin O'Connor ", '-', '-', '-2011', 140.0, 8.2, 71.0)
('Demon Slayer the Movie: Mugen Train', ' Haruo Sotozaki ', '-', '-', '-2020', 117.0, 8.2, 72.0)
('Ran', ' Akira Kurosawa ', '-', '-', '-1985', 162.0, 8.2, 97.0)
('Gangs of Wasseypur', ' Anurag Kashyap ', '-', '-', '-2012', 321.0, 8.2, 89.0)
('Vikram Vedha', ' Gayatri', ' Pushkar', ' Gowtham Selvaraj ', '-2017', 147.0, 8.2, 'NA\n')
('Top Gun: Maverick', ' Joseph Kosinski ', '-', '-', '-2022', 130.0, 8.3, 78.0)
('Heat', ' Michael Mann ', '-', '-', '-1995', 170.0, 8.3, 76.0)
('North by Northwest', ' Alfred Hitchcock ', '-', '-', '-1959', 136.0, 8.3, 98.0)
('Star Wars: Episode VI - Return of the Jedi', ' Richard Marquand ', '-', '-', '-1983', 131.0, 8.3, 58.0)
('Princess Mononoke', ' Hayao Miyazaki ', '-', '-', '-1997', 134.0, 8.3, 76.0)
('Kantara', ' Rishab Shetty ', '-', '-', '-2022', 148.0, 8.3, 'NA\n')
('Dangal', ' Nitesh Tiwari ', '-', '-', '-2016', 161.0, 8.3, 'NA\n')
('Raatchasan', ' Ram Kumar ', '-', '-', '-2018', 170.0, 8.3, 'NA\n')
('K.G.F: Chapter 2', ' Prashanth Neel ', '-', '-', '-2022', 168.0, 8.3, 'NA\n')
('Vikram', ' Lokesh Kanagaraj ', '-', '-', '-2022', 175.0, 8.3, 'NA\n')
('Shershaah', ' Vishnuvardhan ', '-', '-', '-2021', 135.0, 8.3, 'NA\n')
('Spider-Man: Into the Spider-Verse', ' Bob Persichetti', ' Peter Ramsey', ' Rodney Rothman ', '-2018', 117.0, 8.4, 87.0)
('Indiana Jones and the Raiders of the Lost Ark', ' Steven Spielberg ', '-', '-', '-1981', 115.0, 8.4, 85.0)
('Avengers: Endgame', ' Anthony Russo', ' Joe Russo ', '-', '-2019', 181.0, 8.4, 78.0)
('Avengers: Infinity War', ' Anthony Russo', ' Joe Russo ', '-', '-2018', 149.0, 8.4, 68.0)
('Oldboy', ' Park Chan-wook ', '-', '-', '-2003', 101.0, 8.4, 77.0)
('The Dark Knight Rises', ' Christopher Nolan ', '-', '-', '-2012', 164.0, 8.4, 78.0)
('Aliens', ' James Cameron ', '-', '-', '-1986', 137.0, 8.4, 84.0)
('Kaithi', ' Lokesh Kanagaraj ', '-', '-', '-2019', 145.0, 8.4, 'NA\n')
('Asuran', ' Vetrimaaran ', '-', '-', '-2019', 141.0, 8.4, 'NA\n')
('LÃ©on: The Professional', ' Luc Besson ', '-', '-', '-1994', 110.0, 8.5, 64.0)
('Gladiator', ' Ridley Scott ', '-', '-', '-2000', 155.0, 8.5, 67.0)
('Star Wars: Episode IV - A New Hope', ' George Lucas ', '-', '-', '-1977', 121.0, 8.6, 90.0)
('Terminator 2: Judgment Day', ' James Cameron ', '-', '-', '-1991', 137.0, 8.6, 75.0)
('Seven Samurai', ' Akira Kurosawa ', '-', '-', '-1954', 207.0, 8.6, 98.0)
('Harakiri', ' Masaki Kobayashi ', '-', '-', '-1962', 133.0, 8.6, 85.0)
('Sita Ramam', ' Hanu Raghavapudi ', '-', '-', '-2022', 163.0, 8.6, 'NA\n')
('The Matrix', ' Lana Wachowski', ' Lilly Wachowski ', '-', '-1999', 136.0, 8.7, 73.0)
('Star Wars: Episode V - The Empire Strikes Back', ' Irvin Kershner ', '-', '-', '-1980', 124.0, 8.7, 82.0)
('Soorarai Pottru', ' Sudha Kongara ', '-', '-', '-2020', 153.0, 8.7, 'NA\n')
('Inception', ' Christopher Nolan ', '-', '-', '-2010', 148.0, 8.8, 74.0)
('The Lord of the Rings: The Fellowship of the Ring', ' Peter Jackson ', '-', '-', '-2001', 178.0, 8.8, 92.0)
('The Lord of the Rings: The Two Towers', ' Peter Jackson ', '-', '-', '-2002', 179.0, 8.8, 87.0)
('The Dark Knight', ' Christopher Nolan ', '-', '-', '-2008', 152.0, 9, 84.0)
('The Lord of the Rings: The Return of the King', ' Peter Jackson ', '-', '-', '-2003', 201.0, 9, 94.0)
('Spider-Man: Across the Spider-Verse', ' Joaquim Dos Santos', ' Kemp Powers', ' Justin K. Thompson ', '-2023', 140.0, 9.1, 87.0)
('Name', 'Dir1', 'Dir2', 'Dir3', 'Years', 'Runtime', 'Ratings', 'metascore\n')

4) Display all movie names in descending order.

In [30]:
sql="SELECT Name FROM Imdb100 ORDER BY Name DESC"
result=cursor.execute(sql)


for i in result:
    print(i)

('Warrior',)
('Vikram Vedha',)
('Vikram',)
('V for Vendetta',)
('Top Gun: Maverick',)
('The Matrix',)
('The Lord of the Rings: The Two Towers',)
('The Lord of the Rings: The Return of the King',)
('The Lord of the Rings: The Fellowship of the Ring',)
('The Dark Knight Rises',)
('The Dark Knight',)
('Terminator 2: Judgment Day',)
('Star Wars: Episode VI - Return of the Jedi',)
('Star Wars: Episode V - The Empire Strikes Back',)
('Star Wars: Episode IV - A New Hope',)
('Spider-Man: No Way Home',)
('Spider-Man: Into the Spider-Verse',)
('Spider-Man: Across the Spider-Verse',)
('Soorarai Pottru',)
('Sita Ramam',)
('Shershaah',)
('Seven Samurai',)
('Ran',)
('Raatchasan',)
('Princess Mononoke',)
('Oldboy',)
('North by Northwest',)
('Name',)
('LÃ©on: The Professional',)
('Kill Bill: Vol. 1',)
('Kantara',)
('Kaithi',)
('K.G.F: Chapter 2',)
('Jurassic Park',)
('Indiana Jones and the Raiders of the Lost Ark',)
('Indiana Jones and the Last Crusade',)
('Inception',)
('Heat',)
('Harakiri',)
('Guardians of the Galaxy Vol. 3',)
('Gladiator',)
('Gangs of Wasseypur',)
('Die Hard',)
('Demon Slayer the Movie: Mugen Train',)
('Dangal',)
('Batman Begins',)
('Avengers: Infinity War',)
('Avengers: Endgame',)
('Asuran',)
('Aliens',)
('1917',)

5) Display movie name starts with ‘P’ and their rating is greater than 7.

In [31]:
sql="SELECT Name FROM Imdb100 WHERE name LIKE 'P%' AND Ratings>7"
result=cursor.execute(sql)


for i in result:
    print(i)

('Princess Mononoke',)

In [54]:

# execute the statement
cursor.execute("""CREATE TABLE Imdb104 (Name TEXT,Actor1 TEXT,Actor2 TEXT,Actor3 TEXT,Actor4 TEXT,
Genre1 TEXT,Genre2 TEXT,Genre3 TEXT,Votes REAL,Certificate TEXT,gross REAL)""")

In [56]:
pd.read_csv ("C:/Users/Pooja/Downloads/Data/File2.csv")
for row in df2.itertuples():
    cursor.execute("INSERT INTO Imdb104(Name,Actor1,Actor2,Actor3,Actor4,Genre1,Genre2,Genre3,Votes,Certificate,gross)VALUES (?,?,?,?,?,?,?,?,?,?,?);",
                (row.Name, 
                row.Actor1,
                row.Actor2,
                row.Actor3,
                row.Actor4,
                row.Genre1,row.Genre2,row.Genre3,row.Votes,row.Certificate,row.gross)
                )
sqliteConnection.commit()

1) Display all movie names with star Arnold Schwarzenegger in ascending order

In [58]:
sql="SELECT Name FROM Imdb104 WHERE Actor1 LIKE '%Arnold%'"
result=cursor.execute(sql)


for i in result:
    print(i)

('Terminator 2: Judgment Day',)

2) Display all details of the movie with the highest number of votes.

In [60]:
sql="SELECT * FROM Imdb104 WHERE Votes = (SELECT MAX(Votes) FROM Imdb104);"
result=cursor.execute(sql)


for i in result:
    print(i)

('Gangs of Wasseypur', ' Manoj Bajpayee', ' Nawazuddin Siddiqui', ' Tigmanshu Dhulia', ' Richa Chadha', 'Action', ' Comedy', ' Crime', '99,407', 'Not Rated', 'NA')

3) Display movie names with gross collections in descending order.

In [61]:
sql="SELECT Name FROM Imdb104 ORDER BY gross DESC"
result=cursor.execute(sql)


for i in result:
    print(i)

('Spider-Man: Across the Spider-Verse',)
('Soorarai Pottru',)
('Harakiri',)
('Sita Ramam',)
('Kaithi',)
('Asuran',)
('Kantara',)
('Raatchasan',)
('Vikram',)
('Shershaah',)
('Guardians of the Galaxy Vol. 3',)
('Gangs of Wasseypur',)
('Vikram Vedha',)
('Avengers: Endgame',)
('Aliens',)
('Die Hard',)
('Spider-Man: No Way Home',)
('Top Gun: Maverick',)
('V for Vendetta',)
('Kill Bill: Vol. 1',)
('Avengers: Infinity War',)
('Heat',)
('K.G.F: Chapter 2',)
('The Dark Knight',)
('Demon Slayer the Movie: Mugen Train',)
('The Dark Knight Rises',)
('Jurassic Park',)
('Ran',)
('The Lord of the Rings: The Return of the King',)
('The Lord of the Rings: The Two Towers',)
('Star Wars: Episode IV - A New Hope',)
('The Lord of the Rings: The Fellowship of the Ring',)
('Star Wars: Episode VI - Return of the Jedi',)
('Inception',)
('Star Wars: Episode V - The Empire Strikes Back',)
('Indiana Jones and the Raiders of the Lost Ark',)
('Batman Begins',)
('Terminator 2: Judgment Day',)
('Princess Mononoke',)
('Indiana Jones and the Last Crusade',)
('Spider-Man: Into the Spider-Verse',)
('Léon: The Professional',)
('Gladiator',)
('The Matrix',)
('1917',)
('Warrior',)
('North by Northwest',)
('Dangal',)
('Oldboy',)
('Seven Samurai',)

4) Display the gross collection of movies with the star Arnold.

In [62]:
sql="SELECT gross FROM Imdb104 WHERE Actor1 LIKE '%Arnold%'"
result=cursor.execute(sql)


for i in result:
    print(i)

('$204.84M',)

5) Display all details of movies with comedy and action genres.

In [63]:
sql="SELECT * FROM Imdb104 WHERE Genre1 IN ('Comedy','Action') OR Genre2 IN ('Comedy','Action') OR Genre3 IN ('Comedy','Action') "
result=cursor.execute(sql) 


for i in result:
    print(i)

('The Dark Knight', ' Christian Bale', ' Heath Ledger', ' Aaron Eckhart', ' Michael Caine', 'Action', ' Crime', ' Drama', '2,720,714', 'PG-13', '$534.86M')
('The Lord of the Rings: The Return of the King', ' Elijah Wood', ' Viggo Mortensen', ' Ian McKellen', ' Orlando Bloom', 'Action', ' Adventure', ' Drama', '1,888,488', 'PG-13', '$377.85M')
('Inception', ' Leonardo DiCaprio', ' Joseph Gordon-Levitt', ' Elliot Page', ' Ken Watanabe', 'Action', ' Adventure', ' Sci-Fi', '2,415,029', 'PG-13', '$292.58M')
('The Lord of the Rings: The Fellowship of the Ring', ' Elijah Wood', ' Ian McKellen', ' Orlando Bloom', ' Sean Bean', 'Action', ' Adventure', ' Drama', '1,917,095', 'PG-13', '$315.54M')
('The Lord of the Rings: The Two Towers', ' Elijah Wood', ' Ian McKellen', ' Viggo Mortensen', ' Orlando Bloom', 'Action', ' Adventure', ' Drama', '1,704,482', 'PG-13', '$342.55M')
('The Matrix', ' Keanu Reeves', ' Laurence Fishburne', ' Carrie-Anne Moss', ' Hugo Weaving', 'Action', ' Sci-Fi', '-', '1,959,384', 'R', '$171.48M')
('Star Wars: Episode V - The Empire Strikes Back', ' Mark Hamill', ' Harrison Ford', ' Carrie Fisher', ' Billy Dee Williams', 'Action', ' Adventure', ' Fantasy', '1,322,132', 'PG', '$290.48M')
('Soorarai Pottru', ' Suriya', ' Paresh Rawal', ' Urvashi', ' Aparna Balamurali', 'Action', ' Drama', '-', '119,546', 'TV-MA', 'NA')
('Star Wars: Episode IV - A New Hope', ' Mark Hamill', ' Harrison Ford', ' Carrie Fisher', ' Alec Guinness', 'Action', ' Adventure', ' Fantasy', '1,394,569', 'PG', '$322.74M')
('Terminator 2: Judgment Day', ' Arnold Schwarzenegger', ' Linda Hamilton', ' Edward Furlong', ' Robert Patrick', 'Action', ' Sci-Fi', '-', '1,123,864', 'R', '$204.84M')
('Seven Samurai', ' Toshirô Mifune', ' Takashi Shimura', ' Keiko Tsushima', ' Yukiko Shimazaki', 'Action', ' Drama', '-', '353,024', 'Not Rated', '$0.27M')
('Harakiri', ' Tatsuya Nakadai', ' Akira Ishihama', ' Shima Iwashita', ' Tetsurô Tanba', 'Action', ' Drama', ' Mystery', '61,080', 'Not Rated', 'NA')
('Sita Ramam', ' Dulquer Salmaan', ' Mrunal Thakur', ' Rashmika Mandanna', ' Sumanth', 'Action', ' Drama', ' Mystery', '60,080', 'U', 'NA')
('Léon: The Professional', ' Jean Reno', ' Gary Oldman', ' Natalie Portman', ' Danny Aiello', 'Action', ' Crime', ' Drama', '1,190,290', 'R', '$19.50M')
('Gladiator', ' Russell Crowe', ' Joaquin Phoenix', ' Connie Nielsen', ' Oliver Reed', 'Action', ' Adventure', ' Drama', '1,537,247', 'R', '$187.71M')
('Indiana Jones and the Raiders of the Lost Ark', ' Harrison Ford', ' Karen Allen', ' Paul Freeman', ' John Rhys-Davies', 'Action', ' Adventure', '-', '987,533', 'PG', '$248.16M')
('Avengers: Endgame', ' Robert Downey Jr.', ' Chris Evans', ' Mark Ruffalo', ' Chris Hemsworth', 'Action', ' Adventure', ' Drama', '1,181,738', 'PG-13', '$858.37M')
('Avengers: Infinity War', ' Robert Downey Jr.', ' Chris Hemsworth', ' Mark Ruffalo', ' Chris Evans', 'Action', ' Adventure', ' Sci-Fi', '1,125,020', 'PG-13', '$678.82M')
('Oldboy', ' Choi Min-sik', ' Yoo Ji-tae', ' Kang Hye-jeong', ' Kim Byeong-Ok', 'Action', ' Drama', ' Mystery', '596,893', 'R', '$0.71M')
('The Dark Knight Rises', ' Christian Bale', ' Tom Hardy', ' Anne Hathaway', ' Gary Oldman', 'Action', ' Drama', ' Thriller', '1,742,890', 'PG-13', '$448.14M')
('Aliens', ' Sigourney Weaver', ' Michael Biehn', ' Carrie Henn', ' Paul Reiser', 'Action', ' Adventure', ' Sci-Fi', '732,966', 'R', '$85.16M')
('Kaithi', ' Karthi', ' Narain', ' Arjun Das', ' George Maryan', 'Action', ' Adventure', ' Crime', '36,165', 'Not Rated', 'NA')
('Asuran', ' Dhanush', ' Manju Warrier', ' Prakash Raj', ' Pasupathy', 'Action', ' Drama', '-', '31,220', 'Not Rated', 'NA')
('Top Gun: Maverick', ' Tom Cruise', ' Jennifer Connelly', ' Miles Teller', ' Val Kilmer', 'Action', ' Drama', '-', '591,986', 'PG-13', '$718.73M')
('Heat', ' Al Pacino', ' Robert De Niro', ' Val Kilmer', ' Jon Voight', 'Action', ' Crime', ' Drama', '677,168', 'R', '$67.44M')
('North by Northwest', ' Cary Grant', ' Eva Marie Saint', ' James Mason', ' Jessie Royce Landis', 'Action', ' Adventure', ' Mystery', '334,789', 'Approved', '$13.28M')
('Star Wars: Episode VI - Return of the Jedi', ' Mark Hamill', ' Harrison Ford', ' Carrie Fisher', ' Billy Dee Williams', 'Action', ' Adventure', ' Fantasy', '1,078,394', 'PG', '$309.13M')
('Kantara', ' Rishab Shetty', ' Kishore Kumar G.', ' Achyuth Kumar', ' Sapthami Gowda', 'Action', ' Adventure', ' Drama', '95,587', 'Not Rated', 'NA')
('Dangal', ' Aamir Khan', ' Sakshi Tanwar', ' Fatima Sana Shaikh', ' Sanya Malhotra', 'Action', ' Biography', ' Drama', '197,494', 'Not Rated', '$12.39M')
('Raatchasan', ' Vishnu Vishal', ' Amala Paul', ' Radha Ravi', ' Sangili Murugan', 'Action', ' Crime', ' Drama', '46,986', 'Not Rated', 'NA')
('K.G.F: Chapter 2', ' Yash', ' Sanjay Dutt', ' Raveena Tandon', ' Srinidhi Shetty', 'Action', ' Crime', ' Drama', '139,725', 'Not Rated', '$6.60M')
('Vikram', ' Kamal Haasan', ' Vijay Sethupathi', ' Fahadh Faasil', ' Narain', 'Action', ' Crime', ' Thriller', '63,915', 'UA', 'NA')
('Shershaah', ' Sidharth Malhotra', ' Kiara Advani', ' Shiv Panditt', ' Pranay Pachauri', 'Action', ' Biography', ' Drama', '124,855', 'TV-14', 'NA')
('Guardians of the Galaxy Vol. 3', ' Chris Pratt', ' Chukwudi Iwuji', ' Bradley Cooper', ' Pom Klementieff', 'Action', ' Adventure', ' Comedy', '158,924', 'PG-13', 'NA')
('Spider-Man: No Way Home', ' Tom Holland', ' Zendaya', ' Benedict Cumberbatch', ' Jacob Batalon', 'Action', ' Adventure', ' Fantasy', '798,894', 'PG-13', '$804.75M')
('Jurassic Park', ' Sam Neill', ' Laura Dern', ' Jeff Goldblum', ' Richard Attenborough', 'Action', ' Adventure', ' Sci-Fi', '1,014,680', 'PG-13', '$402.45M')
('Indiana Jones and the Last Crusade', ' Harrison Ford', ' Sean Connery', ' Alison Doody', ' Denholm Elliott', 'Action', ' Adventure', '-', '771,853', 'PG-13', '$197.17M')
('1917', ' Dean-Charles Chapman', ' George MacKay', ' Daniel Mays', ' Colin Firth', 'Action', ' Drama', ' War', '621,858', 'R', '$159.23M')
('Batman Begins', ' Christian Bale', ' Michael Caine', ' Ken Watanabe', ' Liam Neeson', 'Action', ' Crime', ' Drama', '1,504,287', 'PG-13', '$206.85M')
('Kill Bill: Vol. 1', ' Uma Thurman', ' David Carradine', ' Daryl Hannah', ' Michael Madsen', 'Action', ' Crime', ' Drama', '1,141,500', 'R', '$70.10M')
('Die Hard', ' Bruce Willis', ' Alan Rickman', ' Bonnie Bedelia', ' Reginald VelJohnson', 'Action', ' Thriller', '-', '901,796', 'R', '$83.01M')
('V for Vendetta', ' Hugo Weaving', ' Natalie Portman', ' Rupert Graves', ' Stephen Rea', 'Action', ' Drama', ' Sci-Fi', '1,141,357', 'R', '$70.51M')
('Warrior', ' Tom Hardy', ' Nick Nolte', ' Joel Edgerton', ' Jennifer Morrison', 'Action', ' Drama', ' Sport', '482,049', 'PG-13', '$13.66M')
('Ran', ' Tatsuya Nakadai', ' Akira Terao', ' Jinpachi Nezu', ' Daisuke Ryû', 'Action', ' Drama', ' War', '129,266', 'R', '$4.14M')
('Gangs of Wasseypur', ' Manoj Bajpayee', ' Nawazuddin Siddiqui', ' Tigmanshu Dhulia', ' Richa Chadha', 'Action', ' Comedy', ' Crime', '99,407', 'Not Rated', 'NA')
('Vikram Vedha', ' Madhavan', ' Vijay Sethupathi', ' Shraddha Srinath', ' Kathir', 'Action', ' Crime', ' Drama', '47,722', 'Not Rated', 'NA')

1) Display all details from both tables where movie names are the same.

In [64]:
sql="SELECT A.*,B.* FROM Imdb100 A INNER JOIN Imdb104 B ON A.Name =B.Name" 
result=cursor.execute(sql)


for i in result:
    print(i)

('Spider-Man: Across the Spider-Verse', ' Joaquim Dos Santos', ' Kemp Powers', ' Justin K. Thompson ', '-2023', 140.0, 9.1, 87.0, 'Spider-Man: Across the Spider-Verse', ' Shameik Moore', ' Hailee Steinfeld', ' Brian Tyree Henry', ' Luna Lauren Velez', 'Animation', ' Action', ' Adventure', '62,493', 'PG', 'NA')
('The Dark Knight', ' Christopher Nolan ', '-', '-', '-2008', 152.0, 9, 84.0, 'The Dark Knight', ' Christian Bale', ' Heath Ledger', ' Aaron Eckhart', ' Michael Caine', 'Action', ' Crime', ' Drama', '2,720,714', 'PG-13', '$534.86M')
('The Lord of the Rings: The Return of the King', ' Peter Jackson ', '-', '-', '-2003', 201.0, 9, 94.0, 'The Lord of the Rings: The Return of the King', ' Elijah Wood', ' Viggo Mortensen', ' Ian McKellen', ' Orlando Bloom', 'Action', ' Adventure', ' Drama', '1,888,488', 'PG-13', '$377.85M')
('Inception', ' Christopher Nolan ', '-', '-', '-2010', 148.0, 8.8, 74.0, 'Inception', ' Leonardo DiCaprio', ' Joseph Gordon-Levitt', ' Elliot Page', ' Ken Watanabe', 'Action', ' Adventure', ' Sci-Fi', '2,415,029', 'PG-13', '$292.58M')
('The Lord of the Rings: The Fellowship of the Ring', ' Peter Jackson ', '-', '-', '-2001', 178.0, 8.8, 92.0, 'The Lord of the Rings: The Fellowship of the Ring', ' Elijah Wood', ' Ian McKellen', ' Orlando Bloom', ' Sean Bean', 'Action', ' Adventure', ' Drama', '1,917,095', 'PG-13', '$315.54M')
('The Lord of the Rings: The Two Towers', ' Peter Jackson ', '-', '-', '-2002', 179.0, 8.8, 87.0, 'The Lord of the Rings: The Two Towers', ' Elijah Wood', ' Ian McKellen', ' Viggo Mortensen', ' Orlando Bloom', 'Action', ' Adventure', ' Drama', '1,704,482', 'PG-13', '$342.55M')
('The Matrix', ' Lana Wachowski', ' Lilly Wachowski ', '-', '-1999', 136.0, 8.7, 73.0, 'The Matrix', ' Keanu Reeves', ' Laurence Fishburne', ' Carrie-Anne Moss', ' Hugo Weaving', 'Action', ' Sci-Fi', '-', '1,959,384', 'R', '$171.48M')
('Star Wars: Episode V - The Empire Strikes Back', ' Irvin Kershner ', '-', '-', '-1980', 124.0, 8.7, 82.0, 'Star Wars: Episode V - The Empire Strikes Back', ' Mark Hamill', ' Harrison Ford', ' Carrie Fisher', ' Billy Dee Williams', 'Action', ' Adventure', ' Fantasy', '1,322,132', 'PG', '$290.48M')
('Soorarai Pottru', ' Sudha Kongara ', '-', '-', '-2020', 153.0, 8.7, 'NA\n', 'Soorarai Pottru', ' Suriya', ' Paresh Rawal', ' Urvashi', ' Aparna Balamurali', 'Action', ' Drama', '-', '119,546', 'TV-MA', 'NA')
('Star Wars: Episode IV - A New Hope', ' George Lucas ', '-', '-', '-1977', 121.0, 8.6, 90.0, 'Star Wars: Episode IV - A New Hope', ' Mark Hamill', ' Harrison Ford', ' Carrie Fisher', ' Alec Guinness', 'Action', ' Adventure', ' Fantasy', '1,394,569', 'PG', '$322.74M')
('Terminator 2: Judgment Day', ' James Cameron ', '-', '-', '-1991', 137.0, 8.6, 75.0, 'Terminator 2: Judgment Day', ' Arnold Schwarzenegger', ' Linda Hamilton', ' Edward Furlong', ' Robert Patrick', 'Action', ' Sci-Fi', '-', '1,123,864', 'R', '$204.84M')
('Seven Samurai', ' Akira Kurosawa ', '-', '-', '-1954', 207.0, 8.6, 98.0, 'Seven Samurai', ' Toshirô Mifune', ' Takashi Shimura', ' Keiko Tsushima', ' Yukiko Shimazaki', 'Action', ' Drama', '-', '353,024', 'Not Rated', '$0.27M')
('Harakiri', ' Masaki Kobayashi ', '-', '-', '-1962', 133.0, 8.6, 85.0, 'Harakiri', ' Tatsuya Nakadai', ' Akira Ishihama', ' Shima Iwashita', ' Tetsurô Tanba', 'Action', ' Drama', ' Mystery', '61,080', 'Not Rated', 'NA')
('Sita Ramam', ' Hanu Raghavapudi ', '-', '-', '-2022', 163.0, 8.6, 'NA\n', 'Sita Ramam', ' Dulquer Salmaan', ' Mrunal Thakur', ' Rashmika Mandanna', ' Sumanth', 'Action', ' Drama', ' Mystery', '60,080', 'U', 'NA')
('Gladiator', ' Ridley Scott ', '-', '-', '-2000', 155.0, 8.5, 67.0, 'Gladiator', ' Russell Crowe', ' Joaquin Phoenix', ' Connie Nielsen', ' Oliver Reed', 'Action', ' Adventure', ' Drama', '1,537,247', 'R', '$187.71M')
('Spider-Man: Into the Spider-Verse', ' Bob Persichetti', ' Peter Ramsey', ' Rodney Rothman ', '-2018', 117.0, 8.4, 87.0, 'Spider-Man: Into the Spider-Verse', ' Shameik Moore', ' Jake Johnson', ' Hailee Steinfeld', ' Mahershala Ali', 'Animation', ' Action', ' Adventure', '573,622', 'PG', '$190.24M')
('Indiana Jones and the Raiders of the Lost Ark', ' Steven Spielberg ', '-', '-', '-1981', 115.0, 8.4, 85.0, 'Indiana Jones and the Raiders of the Lost Ark', ' Harrison Ford', ' Karen Allen', ' Paul Freeman', ' John Rhys-Davies', 'Action', ' Adventure', '-', '987,533', 'PG', '$248.16M')
('Avengers: Endgame', ' Anthony Russo', ' Joe Russo ', '-', '-2019', 181.0, 8.4, 78.0, 'Avengers: Endgame', ' Robert Downey Jr.', ' Chris Evans', ' Mark Ruffalo', ' Chris Hemsworth', 'Action', ' Adventure', ' Drama', '1,181,738', 'PG-13', '$858.37M')
('Avengers: Infinity War', ' Anthony Russo', ' Joe Russo ', '-', '-2018', 149.0, 8.4, 68.0, 'Avengers: Infinity War', ' Robert Downey Jr.', ' Chris Hemsworth', ' Mark Ruffalo', ' Chris Evans', 'Action', ' Adventure', ' Sci-Fi', '1,125,020', 'PG-13', '$678.82M')
('Oldboy', ' Park Chan-wook ', '-', '-', '-2003', 101.0, 8.4, 77.0, 'Oldboy', ' Choi Min-sik', ' Yoo Ji-tae', ' Kang Hye-jeong', ' Kim Byeong-Ok', 'Action', ' Drama', ' Mystery', '596,893', 'R', '$0.71M')
('The Dark Knight Rises', ' Christopher Nolan ', '-', '-', '-2012', 164.0, 8.4, 78.0, 'The Dark Knight Rises', ' Christian Bale', ' Tom Hardy', ' Anne Hathaway', ' Gary Oldman', 'Action', ' Drama', ' Thriller', '1,742,890', 'PG-13', '$448.14M')
('Aliens', ' James Cameron ', '-', '-', '-1986', 137.0, 8.4, 84.0, 'Aliens', ' Sigourney Weaver', ' Michael Biehn', ' Carrie Henn', ' Paul Reiser', 'Action', ' Adventure', ' Sci-Fi', '732,966', 'R', '$85.16M')
('Kaithi', ' Lokesh Kanagaraj ', '-', '-', '-2019', 145.0, 8.4, 'NA\n', 'Kaithi', ' Karthi', ' Narain', ' Arjun Das', ' George Maryan', 'Action', ' Adventure', ' Crime', '36,165', 'Not Rated', 'NA')
('Asuran', ' Vetrimaaran ', '-', '-', '-2019', 141.0, 8.4, 'NA\n', 'Asuran', ' Dhanush', ' Manju Warrier', ' Prakash Raj', ' Pasupathy', 'Action', ' Drama', '-', '31,220', 'Not Rated', 'NA')
('Top Gun: Maverick', ' Joseph Kosinski ', '-', '-', '-2022', 130.0, 8.3, 78.0, 'Top Gun: Maverick', ' Tom Cruise', ' Jennifer Connelly', ' Miles Teller', ' Val Kilmer', 'Action', ' Drama', '-', '591,986', 'PG-13', '$718.73M')
('Heat', ' Michael Mann ', '-', '-', '-1995', 170.0, 8.3, 76.0, 'Heat', ' Al Pacino', ' Robert De Niro', ' Val Kilmer', ' Jon Voight', 'Action', ' Crime', ' Drama', '677,168', 'R', '$67.44M')
('North by Northwest', ' Alfred Hitchcock ', '-', '-', '-1959', 136.0, 8.3, 98.0, 'North by Northwest', ' Cary Grant', ' Eva Marie Saint', ' James Mason', ' Jessie Royce Landis', 'Action', ' Adventure', ' Mystery', '334,789', 'Approved', '$13.28M')
('Star Wars: Episode VI - Return of the Jedi', ' Richard Marquand ', '-', '-', '-1983', 131.0, 8.3, 58.0, 'Star Wars: Episode VI - Return of the Jedi', ' Mark Hamill', ' Harrison Ford', ' Carrie Fisher', ' Billy Dee Williams', 'Action', ' Adventure', ' Fantasy', '1,078,394', 'PG', '$309.13M')
('Princess Mononoke', ' Hayao Miyazaki ', '-', '-', '-1997', 134.0, 8.3, 76.0, 'Princess Mononoke', ' Yôji Matsuda', ' Yuriko Ishida', ' Yûko Tanaka', ' Billy Crudup', 'Animation', ' Action', ' Adventure', '407,126', 'PG-13', '$2.38M')
('Kantara', ' Rishab Shetty ', '-', '-', '-2022', 148.0, 8.3, 'NA\n', 'Kantara', ' Rishab Shetty', ' Kishore Kumar G.', ' Achyuth Kumar', ' Sapthami Gowda', 'Action', ' Adventure', ' Drama', '95,587', 'Not Rated', 'NA')
('Dangal', ' Nitesh Tiwari ', '-', '-', '-2016', 161.0, 8.3, 'NA\n', 'Dangal', ' Aamir Khan', ' Sakshi Tanwar', ' Fatima Sana Shaikh', ' Sanya Malhotra', 'Action', ' Biography', ' Drama', '197,494', 'Not Rated', '$12.39M')
('Raatchasan', ' Ram Kumar ', '-', '-', '-2018', 170.0, 8.3, 'NA\n', 'Raatchasan', ' Vishnu Vishal', ' Amala Paul', ' Radha Ravi', ' Sangili Murugan', 'Action', ' Crime', ' Drama', '46,986', 'Not Rated', 'NA')
('K.G.F: Chapter 2', ' Prashanth Neel ', '-', '-', '-2022', 168.0, 8.3, 'NA\n', 'K.G.F: Chapter 2', ' Yash', ' Sanjay Dutt', ' Raveena Tandon', ' Srinidhi Shetty', 'Action', ' Crime', ' Drama', '139,725', 'Not Rated', '$6.60M')
('Vikram', ' Lokesh Kanagaraj ', '-', '-', '-2022', 175.0, 8.3, 'NA\n', 'Vikram', ' Kamal Haasan', ' Vijay Sethupathi', ' Fahadh Faasil', ' Narain', 'Action', ' Crime', ' Thriller', '63,915', 'UA', 'NA')
('Shershaah', ' Vishnuvardhan ', '-', '-', '-2021', 135.0, 8.3, 'NA\n', 'Shershaah', ' Sidharth Malhotra', ' Kiara Advani', ' Shiv Panditt', ' Pranay Pachauri', 'Action', ' Biography', ' Drama', '124,855', 'TV-14', 'NA')
('Guardians of the Galaxy Vol. 3', ' James Gunn ', '-', '-', '-2023', 150.0, 8.2, 64.0, 'Guardians of the Galaxy Vol. 3', ' Chris Pratt', ' Chukwudi Iwuji', ' Bradley Cooper', ' Pom Klementieff', 'Action', ' Adventure', ' Comedy', '158,924', 'PG-13', 'NA')
('Spider-Man: No Way Home', ' Jon Watts ', '-', '-', '-2021', 148.0, 8.2, 71.0, 'Spider-Man: No Way Home', ' Tom Holland', ' Zendaya', ' Benedict Cumberbatch', ' Jacob Batalon', 'Action', ' Adventure', ' Fantasy', '798,894', 'PG-13', '$804.75M')
('Jurassic Park', ' Steven Spielberg ', '-', '-', '-1993', 127.0, 8.2, 68.0, 'Jurassic Park', ' Sam Neill', ' Laura Dern', ' Jeff Goldblum', ' Richard Attenborough', 'Action', ' Adventure', ' Sci-Fi', '1,014,680', 'PG-13', '$402.45M')
('Indiana Jones and the Last Crusade', ' Steven Spielberg ', '-', '-', '-1989', 127.0, 8.2, 65.0, 'Indiana Jones and the Last Crusade', ' Harrison Ford', ' Sean Connery', ' Alison Doody', ' Denholm Elliott', 'Action', ' Adventure', '-', '771,853', 'PG-13', '$197.17M')
('1917', ' Sam Mendes ', '-', '-', '-2019', 119.0, 8.2, 78.0, '1917', ' Dean-Charles Chapman', ' George MacKay', ' Daniel Mays', ' Colin Firth', 'Action', ' Drama', ' War', '621,858', 'R', '$159.23M')
('Batman Begins', ' Christopher Nolan ', '-', '-', '-2005', 140.0, 8.2, 70.0, 'Batman Begins', ' Christian Bale', ' Michael Caine', ' Ken Watanabe', ' Liam Neeson', 'Action', ' Crime', ' Drama', '1,504,287', 'PG-13', '$206.85M')
('Kill Bill: Vol. 1', ' Quentin Tarantino ', '-', '-', '-2003', 111.0, 8.2, 69.0, 'Kill Bill: Vol. 1', ' Uma Thurman', ' David Carradine', ' Daryl Hannah', ' Michael Madsen', 'Action', ' Crime', ' Drama', '1,141,500', 'R', '$70.10M')
('Die Hard', ' John McTiernan ', '-', '-', '-1988', 132.0, 8.2, 72.0, 'Die Hard', ' Bruce Willis', ' Alan Rickman', ' Bonnie Bedelia', ' Reginald VelJohnson', 'Action', ' Thriller', '-', '901,796', 'R', '$83.01M')
('V for Vendetta', ' James McTeigue ', '-', '-', '-2005', 132.0, 8.2, 62.0, 'V for Vendetta', ' Hugo Weaving', ' Natalie Portman', ' Rupert Graves', ' Stephen Rea', 'Action', ' Drama', ' Sci-Fi', '1,141,357', 'R', '$70.51M')
('Warrior', " Gavin O'Connor ", '-', '-', '-2011', 140.0, 8.2, 71.0, 'Warrior', ' Tom Hardy', ' Nick Nolte', ' Joel Edgerton', ' Jennifer Morrison', 'Action', ' Drama', ' Sport', '482,049', 'PG-13', '$13.66M')
('Demon Slayer the Movie: Mugen Train', ' Haruo Sotozaki ', '-', '-', '-2020', 117.0, 8.2, 72.0, 'Demon Slayer the Movie: Mugen Train', ' Natsuki Hanae', ' Akari Kitô', ' Yoshitsugu Matsuoka', ' Hiro Shimono', 'Animation', ' Action', ' Adventure', '64,529', 'R', '$47.70M')
('Ran', ' Akira Kurosawa ', '-', '-', '-1985', 162.0, 8.2, 97.0, 'Ran', ' Tatsuya Nakadai', ' Akira Terao', ' Jinpachi Nezu', ' Daisuke Ryû', 'Action', ' Drama', ' War', '129,266', 'R', '$4.14M')
('Gangs of Wasseypur', ' Anurag Kashyap ', '-', '-', '-2012', 321.0, 8.2, 89.0, 'Gangs of Wasseypur', ' Manoj Bajpayee', ' Nawazuddin Siddiqui', ' Tigmanshu Dhulia', ' Richa Chadha', 'Action', ' Comedy', ' Crime', '99,407', 'Not Rated', 'NA')
('Vikram Vedha', ' Gayatri', ' Pushkar', ' Gowtham Selvaraj ', '-2017', 147.0, 8.2, 'NA\n', 'Vikram Vedha', ' Madhavan', ' Vijay Sethupathi', ' Shraddha Srinath', ' Kathir', 'Action', ' Crime', ' Drama', '47,722', 'Not Rated', 'NA')

2) Display all movie names, Director, ratings, and gross collection where the genre is action.

In [66]:
sql="SELECT A.Name,A.Dir1,A.Dir2,A.Dir3,A.Ratings,B.gross FROM Imdb100 A INNER JOIN Imdb104 B ON A.Name =B.Name WHERE Genre1='Action'" 
result=cursor.execute(sql)


for i in result:
    print(i)

('The Dark Knight', ' Christopher Nolan ', '-', '-', 9, '$534.86M')
('The Lord of the Rings: The Return of the King', ' Peter Jackson ', '-', '-', 9, '$377.85M')
('Inception', ' Christopher Nolan ', '-', '-', 8.8, '$292.58M')
('The Lord of the Rings: The Fellowship of the Ring', ' Peter Jackson ', '-', '-', 8.8, '$315.54M')
('The Lord of the Rings: The Two Towers', ' Peter Jackson ', '-', '-', 8.8, '$342.55M')
('The Matrix', ' Lana Wachowski', ' Lilly Wachowski ', '-', 8.7, '$171.48M')
('Star Wars: Episode V - The Empire Strikes Back', ' Irvin Kershner ', '-', '-', 8.7, '$290.48M')
('Soorarai Pottru', ' Sudha Kongara ', '-', '-', 8.7, 'NA')
('Star Wars: Episode IV - A New Hope', ' George Lucas ', '-', '-', 8.6, '$322.74M')
('Terminator 2: Judgment Day', ' James Cameron ', '-', '-', 8.6, '$204.84M')
('Seven Samurai', ' Akira Kurosawa ', '-', '-', 8.6, '$0.27M')
('Harakiri', ' Masaki Kobayashi ', '-', '-', 8.6, 'NA')
('Sita Ramam', ' Hanu Raghavapudi ', '-', '-', 8.6, 'NA')
('Gladiator', ' Ridley Scott ', '-', '-', 8.5, '$187.71M')
('Indiana Jones and the Raiders of the Lost Ark', ' Steven Spielberg ', '-', '-', 8.4, '$248.16M')
('Avengers: Endgame', ' Anthony Russo', ' Joe Russo ', '-', 8.4, '$858.37M')
('Avengers: Infinity War', ' Anthony Russo', ' Joe Russo ', '-', 8.4, '$678.82M')
('Oldboy', ' Park Chan-wook ', '-', '-', 8.4, '$0.71M')
('The Dark Knight Rises', ' Christopher Nolan ', '-', '-', 8.4, '$448.14M')
('Aliens', ' James Cameron ', '-', '-', 8.4, '$85.16M')
('Kaithi', ' Lokesh Kanagaraj ', '-', '-', 8.4, 'NA')
('Asuran', ' Vetrimaaran ', '-', '-', 8.4, 'NA')
('Top Gun: Maverick', ' Joseph Kosinski ', '-', '-', 8.3, '$718.73M')
('Heat', ' Michael Mann ', '-', '-', 8.3, '$67.44M')
('North by Northwest', ' Alfred Hitchcock ', '-', '-', 8.3, '$13.28M')
('Star Wars: Episode VI - Return of the Jedi', ' Richard Marquand ', '-', '-', 8.3, '$309.13M')
('Kantara', ' Rishab Shetty ', '-', '-', 8.3, 'NA')
('Dangal', ' Nitesh Tiwari ', '-', '-', 8.3, '$12.39M')
('Raatchasan', ' Ram Kumar ', '-', '-', 8.3, 'NA')
('K.G.F: Chapter 2', ' Prashanth Neel ', '-', '-', 8.3, '$6.60M')
('Vikram', ' Lokesh Kanagaraj ', '-', '-', 8.3, 'NA')
('Shershaah', ' Vishnuvardhan ', '-', '-', 8.3, 'NA')
('Guardians of the Galaxy Vol. 3', ' James Gunn ', '-', '-', 8.2, 'NA')
('Spider-Man: No Way Home', ' Jon Watts ', '-', '-', 8.2, '$804.75M')
('Jurassic Park', ' Steven Spielberg ', '-', '-', 8.2, '$402.45M')
('Indiana Jones and the Last Crusade', ' Steven Spielberg ', '-', '-', 8.2, '$197.17M')
('1917', ' Sam Mendes ', '-', '-', 8.2, '$159.23M')
('Batman Begins', ' Christopher Nolan ', '-', '-', 8.2, '$206.85M')
('Kill Bill: Vol. 1', ' Quentin Tarantino ', '-', '-', 8.2, '$70.10M')
('Die Hard', ' John McTiernan ', '-', '-', 8.2, '$83.01M')
('V for Vendetta', ' James McTeigue ', '-', '-', 8.2, '$70.51M')
('Warrior', " Gavin O'Connor ", '-', '-', 8.2, '$13.66M')
('Ran', ' Akira Kurosawa ', '-', '-', 8.2, '$4.14M')
('Gangs of Wasseypur', ' Anurag Kashyap ', '-', '-', 8.2, 'NA')
('Vikram Vedha', ' Gayatri', ' Pushkar', ' Gowtham Selvaraj ', 8.2, 'NA')

3) Display all details from both tables with the highest gross collection.

In [89]:
sql="SELECT MAX(B.gross),A.*,B.* FROM Imdb104 B INNER JOIN Imdb100 A ON A.Name =B.Name;" 
result=cursor.execute(sql)


for i in result:
    print(i)

('NA', 'Spider-Man: Across the Spider-Verse', ' Joaquim Dos Santos', ' Kemp Powers', ' Justin K. Thompson ', '-2023', 140.0, 9.1, 87.0, 'Spider-Man: Across the Spider-Verse', ' Shameik Moore', ' Hailee Steinfeld', ' Brian Tyree Henry', ' Luna Lauren Velez', 'Animation', ' Action', ' Adventure', '62,493', 'PG', 'NA')

4) Display all details from both tables with the highest ratings

In [88]:
sql="SELECT A.*,B.*,MAX(A.Ratings) FROM Imdb100 A INNER JOIN Imdb104 B ON A.Name =B.Name ;" 
result=cursor.execute(sql)


for i in result:
    print(i)

('Spider-Man: Across the Spider-Verse', ' Joaquim Dos Santos', ' Kemp Powers', ' Justin K. Thompson ', '-2023', 140.0, 9.1, 87.0, 'Spider-Man: Across the Spider-Verse', ' Shameik Moore', ' Hailee Steinfeld', ' Brian Tyree Henry', ' Luna Lauren Velez', 'Animation', ' Action', ' Adventure', '62,493', 'PG', 'NA', 9.1)

 Display all details from both tables with the lowest gross collection and lowest ratings

In [97]:
sql="SELECT A.*,B.* ,MIN(B.gross) AND MIN(A.Ratings) FROM Imdb100 A INNER JOIN Imdb104 B ON A.Name =B.Name ;" 
result=cursor.execute(sql)


for i in result:
    print(i)

('Guardians of the Galaxy Vol. 3', ' James Gunn ', '-', '-', '-2023', 150.0, 8.2, 64.0, 'Guardians of the Galaxy Vol. 3', ' Chris Pratt', ' Chukwudi Iwuji', ' Bradley Cooper', ' Pom Klementieff', 'Action', ' Adventure', ' Comedy', '158,924', 'PG-13', 'NA', 0)